<?php
use Dfe\Color\Image as I;
$folder = 'mage2pro';
$dir = df_media_path_absolute($folder);
echo df_tag('div', 'dfe-color', implode(df_map(array_slice(scandir($dir), 2), function(string $c) use($folder) {
	$url = df_media_path2url("$folder/$c"); /** @var string $url */
	$i = new I(df_media_path_absolute("$folder/$c"));
	return df_tag('div', [], [
		df_tag('a', ['title' => $c, 'url' => $url], df_tag('img', ['src' => $url]))
		,df_tag('ol', [], implode(df_map_k($i->labels(), function($l, $v) {return df_tag('li', [], [
			df_tag('span', [], $l), df_tag('span', [], "$v%")
		]);})))
	]);
})));